# This is a workflow for the hometask.node project

name: CI for hometask.node

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to the "main" branch
  push:
    branches:
      - main

  # Triggers the workflow on pull request events with types "opened" and "synchronize"
  pull_request:
    types:
      - opened
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
  
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Node.js and npm
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run:   
          npm test


  # This job is responsible for creating and accepting a pull request
  create_and_accept_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Create a new branch
      - name: Create new branch
        run: |
          git checkout -b feature/update-code
          git push origin feature/update-code

      # Create a pull request
      - name: Create pull request
        uses: marianamartsy/hometask.node
        with:
          token: ${{ secrets.TOKEN }}
          branch: feature/update-code
          title: "Update project code"
          body: "This pull request updates the project code in response to CI."

