# This is a workflow for the hometask.node project

name: CI for hometask.node

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to the "main" branch
  push:
    branches: [ "main" ]

  # Triggers the workflow on pull request events with types "opened" and "synchronize"
  pull_request:
    types:
      - opened
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is responsible for building and testing the hometask.node project
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Run the workflow only when triggered by a push event to the main branch
      - name: Check branch
        run: |
          if [[ ${{ github.ref }} != 'refs/heads/main' ]]; then
            echo "This workflow only runs on the main branch. Exiting..."
            exit 78
          fi

      # Install Node.js and npm
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Build and test the project
      - name: Build and test project
        run: |
          npm start
          npm test

      # Update the repository with the modified code
      - name: Update code in repository
        run: |
          # Add commands to commit and push the modified code

      # Add a link to the workflow in the repository
      - name: Add workflow link
        run: |
          # Add commands to print a link to the workflow run

  # This job is responsible for creating and accepting a pull request
  create_and_accept_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Create a new branch
      - name: Create new branch
        run: |
          git checkout -b feature/update-code
          git push origin feature/update-code

      # Create a pull request
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/update-code
          title: "Update project code"
          body: "This pull request updates the project code in response to CI."

      # Accept the pull request
      - name: Accept pull request
        run: |
          # Add commands to accept the pull request
