name: Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Verify script execution
        run: echo "Script executed successfully"

      - name: Create new branch for PR
        run: git checkout -b ci-pr-${{ github.run_id }}

      - name: Commit changes
        run: |
          git config user.name "mariana"
          git config user.email "mart7mariana@gmail.com"
          git commit -am "CI: Automated changes"
          git push origin ci-pr-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
          commit-message: "Automated PR from CI"
          title: Automated CI Pull Request
          body: |
            This PR was automatically generated by the CI workflow.
